/**
 * swagger_full_client
 * Doc API
 *
 * OpenAPI spec version: 2.42.0
 * Contact: contact@jak.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Contains the Single GPS points.
 */
export interface ApiGpsPoint {
    gps_id?: number;

    /**
     * This field will be generate by backend
     */
    formatted_address?: string;

    /**
     * @deprecated since version 2.38. Address
     */
    gps_address?: string;

    /**
     * Postal code
     */
    postal_code?: string;

    street_number?: string;

    route?: string;

    locality?: string;

    area_level_1?: string;

    area_level_2?: string;

    country?: string;

    /**
     * @deprecated since version 2.0
     */
    gps_city?: string;

    gps_lat?: number;

    gps_lon?: number;

    /**
     * 380;GPS_ENTERPRISE 381;GPS_HOUSE 382;GPS_MEETING 383;GPS_STARTING 384;GPS_STOPPING 385;GPS_ALGO 386;GPS_PARKING 387;GPS_PERSO
     */
    gps_type?: number;

    gps_lib?: string;

    place_id?: string;

    /**
     * Description of places
     */
    type?: Array<string>;

    /**
     * distance in km
     */
    distance?: number;

    // utc_offset_minutes?: number;
}
