export class Minute {
  constructor(
    public numero: number,
    public secteur: number,
    public support: string,
    public remarques: string,
    public email: string,
    public faits: number[],
    public faitGenre: string,
    public faitEchelle: string,
    public faitRemarques: string,
    public unite_ids: number[],
    public uniteGenre: string,
    public uniteEchelle: string,
    public uniteRemarques: string,
    public ensembles: number[],
    public ensembleGenre: string,
    public ensembleEchelle: string,
    public ensembleRemarques: string,
    public sondages: number[],
    public sondageGenre: string,
    public sondageEchelle: string,
    public sondageRemarques: string,
    public topos: number[],
    public topoGenre: string,
    public topoRemarques: string,
    public levee: string,
  ) {}
}
