export class Numerotation {
  constructor(
    public typeNumFait: string,
    public prefixeFait: string,
    public numDepartFait: number,
    public typeNumUnite: string,
    public prefixeUnite: string,
    public numDepartUnite: number,
    public typeNumEnsemble: string,
    public prefixeEnsemble: string,
    public numDepartEnsemble: number,
    public typeNumSondage: string,
    public prefixeSondage: string,
    public numDepartSondage: number,
    public typeNumCoupe: string,
    public prefixeCoupe: string,
    public numDepartCoupe: number,
    public typeNumMobilier: string,
    public prefixeMobilier: string,
    public numDepartMobilier: number,
    public typeNumPrelevement: string,
    public prefixePrelevement: string,
    public numDepartPrelevement: number,
    public typeNumContenant: string,
    public prefixeContenantBac: string,
    public prefixeContenantBoite: string,
    public numDepartContenantBac: number,
    public numDepartContenantBoite: number,
    public typeNumMinute: string,
    public prefixeMinute: string,
    public numDepartMinute: number,
    public typeNumPhoto: string,
    public prefixePhoto: string,
    public numDepartPhoto: number,
    public typeNumPointTopo: string,
    public prefixePointTopo: string,
    public numDepartPointTopo: number,
  ) {}
}
