export enum ApiSynchroFrontInterfaceEnum {
    INTERFACE_HOME,
    INTERFACE_AUTHENTICATION,
    INTERFACE_PROFILE,
    // PROJECT route
    INTERFACE_PROJECT_LIST,
    INTERFACE_PROJECT_NEW,
    INTERFACE_PROJECT_EDIT,
    INTERFACE_PROJECT_DASH,
    INTERFACE_PROJECT_STATISTICS,
    INTERFACE_PROJECT_CONFIGURATION,
    // SECTOR route
    INTERFACE_SECTOR_LIST,
    INTERFACE_SECTOR_DETAILS,
    INTERFACE_SECTOR_NEW,
    // ENSEMBLE route
    INTERFACE_ENSEMBLE_LIST,
    INTERFACE_ENSEMBLE_DETAILS,
    INTERFACE_ENSEMBLE_NEW,
    // FAIT route
    INTERFACE_FAIT_LIST,
    INTERFACE_FAIT_DETAILS,
    INTERFACE_FAIT_NEW,
    // US (Unite) route
    INTERFACE_US_LIST,
    INTERFACE_US_DETAILS,
    INTERFACE_US_NEW,
    // MINUTES route
    INTERFACE_MINUTE_LIST,
    INTERFACE_MINUTE_DETAILS,
    INTERFACE_MINUTE_NEW,
    // SONDAGE route
    INTERFACE_SONDAGE_LIST,
    INTERFACE_SONDAGE_DETAILS,
    INTERFACE_SONDAGE_NEW,
    // Mobilier route
    INTERFACE_MOBILIER_LIST,
    INTERFACE_MOBILIER_DETAILS,
    INTERFACE_MOBILIER_NEW,
    // Prelevement route
    INTERFACE_PRELEVEMENT_LIST,
    INTERFACE_PRELEVEMENT_DETAILS,
    INTERFACE_PRELEVEMENT_NEW,
    // Contenants route
    INTERFACE_CONTENANTS_LIST,
    INTERFACE_CONTENANTS_DETAILS,
    INTERFACE_CONTENANTS_NEW,
    // Photos route
    INTERFACE_PHOTOS_LIST,
    INTERFACE_PHOTOS_DETAILS,
    INTERFACE_PHOTOS_NEW,
    // Topos route
    INTERFACE_TOPOS_LIST,
    INTERFACE_TOPOS_DETAILS,
    INTERFACE_TOPOS_NEW,

    INTERFACE_IDENTIFICATIONS,
    INTERFACE_FAIT_IDENTIFICATION,
    INTERFACE_ENSEMBLE_IDENTIFICATIONS,

}
